# Numpy

In [2]:
import numpy as np

## Create array using numpy
## Create a 1d array

arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [11]:
print(arr1.shape)

(6,)


In [12]:
arr2=np.array([1,2,3,4,5,6])
arr2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [17]:
#2d array
arr3=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3.shape)
print(arr3)

(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]


In [20]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#identity matrix
np.eye(3)

In [23]:
#attributes of array
arr= np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimension",arr.ndim)
print("Size (number of elements)",arr.size)
print("Data type",arr.dtype)
print("Item sixe :",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimension 2
Size (number of elements) 6
Data type int32
Item sixe : 4


In [24]:
### numpy Vectorized operation

arr1=np.array([1,2,3,4,5])
arr3=np.array([10,20,30,40,50])

#Element Wise Addition
print("Addition :",arr1+arr3)

#Element wise Substraction
print("Substraction :",arr1-arr3)

#Element wise Multion
print("Multion :",arr1*arr3)

#Element wise Diviion
print("Diviion :",arr1/arr3)



Addition : [11 22 33 44 55]
Substraction : [ -9 -18 -27 -36 -45]
Multion : [ 10  40  90 160 250]
Diviion : [0.1 0.1 0.1 0.1 0.1]


In [26]:
#Universal operation

arr=np.array([2,3,4,5,6])

#square root
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

#natural log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [31]:
# array  slicing and indexing 

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [47]:
print(arr[0][0])
print(arr[1:,1:3])

1
[[ 6  7]
 [10 11]]


In [36]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [40]:
print(arr[1:])

array([[ 2],
       [ 6],
       [10]])

In [46]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [49]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
## Modify element
arr[0][0]=101


In [58]:
arr

array([[101,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [59]:
arr[1:]=100

In [60]:
arr

array([[101,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [61]:
#Statistical concepts -- Normaliztion
#to have a mean of 0 and standard deviation of 1
data= np.array([1,2,3,4,5])

#calculate the mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

#normalize the data
normalize_data=(data-mean)/std_dev
print("Normalized data",normalize_data)


Normalized data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [63]:
#logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>5) & (data<=8)]

array([6, 7, 8])